using M223PunchclockDotnet.Model;
using Microsoft.EntityFrameworkCore;

namespace M223PunchclockDotnet;

public static class DbInitializer
{
    public static void Initialize(DatabaseContext context)
    {
        context.Database.ExecuteSql($"DROP TABLE IF EXISTS \"EntryTag\"");
        context.Database.ExecuteSql($"DROP TABLE IF EXISTS \"Tag\"");
        context.Database.ExecuteSql($"DROP TABLE IF EXISTS \"Entry\"");
        context.Database.ExecuteSql($"DROP TABLE IF EXISTS \"Category\"");
        
        context.Database.ExecuteSql($"""
                                      CREATE TABLE public."Category"(
                                         "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ), 
                                         "Title" VARCHAR(255) NOT NULL,
                                         CONSTRAINT "PK_Category" PRIMARY KEY ("Id"))
                                     """);
        
        context.Database.ExecuteSql($"""
                                      CREATE TABLE public."Entry"(
                                         "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ), 
                                         "CheckIn" timestamp with time zone NOT NULL,
                                         "CheckOut" timestamp with time zone NOT NULL,
                                         "CategoryId" integer NOT NULL,
                                         CONSTRAINT "PK_Entry" PRIMARY KEY ("Id"),
                                         CONSTRAINT "FK_Category" FOREIGN KEY ("CategoryId") REFERENCES public."Category"("Id"))
                                    """);
        
        context.Database.ExecuteSql($"""
                                      CREATE TABLE public."Tag"(
                                         "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ), 
                                         "Title" VARCHAR(255) NOT NULL,
                                         CONSTRAINT "PK_Tag" PRIMARY KEY ("Id"))
                                     """);
        
        context.Database.ExecuteSql($"""
                                     CREATE TABLE public."EntryTag"(
                                        "EntryId" integer NOT NULL,
                                        "TagId" integer NOT NULL,
                                        CONSTRAINT "FK_Entry" FOREIGN KEY ("EntryId") REFERENCES public."Entry"("Id"),
                                        CONSTRAINT "FK_Tag" FOREIGN KEY ("TagId") REFERENCES public."Tag"("Id"))
                                     """);
    }

    public static void InsertExampleData(DatabaseContext context)
    {
        context.Database.ExecuteSql($"""
                                     INSERT INTO public."Category" ("Title") VALUES ('this is a sample category');
                                     INSERT INTO public."Entry" ("CheckIn", "CheckOut", "CategoryId") VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1));
                                     INSERT INTO public."Tag" ("Title") VALUES ('this is a sample tag'); 
                                     INSERT INTO public."EntryTag" ("EntryId", "TagId") VALUES (1, 1);
                                     """);
    }
}